"""Create table books

Revision ID: 0817994fdbf9
Revises: 
Create Date: 2022-08-18 16:04:51.060065

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from faker import Faker

from models import Book


# revision identifiers, used by Alembic.
revision = '0817994fdbf9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    engine = create_engine('sqlite:///bookstore.db')
    session = sessionmaker(bind=engine)()

    print("Seeding books...")

    fake = Faker()

    books = [
        Book(
            title=fake.name(),
            author=fake.name(),
            publisher=fake.name(),
            publish_date=fake.date_time().date(),
        )
    for i in range(50)]

    session.bulk_save_objects(books)
    session.commit()
    session.close()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
