"""Add table salespeople

Revision ID: a7323c275f5a
Revises: 0817994fdbf9
Create Date: 2022-08-18 21:47:42.059339

"""

from random import randint

from alembic import op
import sqlalchemy as sa
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from faker import Faker

from models import Book, Salesperson


# revision identifiers, used by Alembic.
revision = 'a7323c275f5a'
down_revision = '0817994fdbf9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salespeople',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('last_clocked_in', sa.DateTime(), nullable=True),
    sa.Column('last_clocked_out', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('books', sa.Column('cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'cost')
    op.drop_table('salespeople')
    # ### end Alembic commands ###
